# Generated by Django 5.0.2 on 2024-12-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
