# Generated by Django 5.0.2 on 2024-12-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_contact_phone_contact_project_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='contact',
            name='project',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
